name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPublish: 'Sources'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishAsArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - template: AzureDevOps/Templates/StepTemplates/NetCore/Initialize_And_Test.yaml@ALMStuff

