name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndSaveArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - template: AzureDevOps/Templates/JobTemplates/Angular/Build_And_Save_Artifact.yaml@ALMStuff