name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller


jobs:
- template: AzureDevOpsAzureDevOps/BuildTemplates/Angular/Pipelines/Angular-SaveArtifact@ALMStuff
  parameters:
    ZipArtifacts: false